Imported Upstream version 0.19.3

diff --git a/gettext-tools/tests/lang-smalltalk b/gettext-tools/tests/lang-smalltalk
--- a/gettext-tools/tests/lang-smalltalk
+++ b/gettext-tools/tests/lang-smalltalk
@@ -1,13 +1,10 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the GNU smalltalk language.
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: smalltalk.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.st"
 cat <<\EOF > prog.st
 PackageLoader fileInPackage: 'I18N' !
 
@@ -33,14 +30,10 @@ run
 Main new run!
 EOF
 
-tmpfiles="$tmpfiles prog.tmp prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.tmp --omit-header --no-location prog.st
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.st || exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -59,7 +52,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} prog.ok prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
 cat <<\EOF > fr.po
 msgid ""
 msgstr ""
@@ -82,17 +74,13 @@ msgid "%1 is replaced by %2."
 msgstr "%2 remplace %1."
 EOF
 
-tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
@@ -101,13 +89,12 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of gst version 2.0.6 or newer.
 (gst --version) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: gst not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: gst not found"; exit 77; }
 case `gst --version | sed -n -e 1p | sed -e 's/^[^0-9]*//'` in
   0.* | 1.* | 2.0 | 2.0.[0-5] | 2.1 | 2.1.[0-1])
-    echo "Skipping test: gst version too old"; rm -fr $tmpfiles; exit 77;;
+    echo "Skipping test: gst version too old"; exit 77;;
 esac
 
-tmpfiles="$tmpfiles prog.ok prog.oku prog.ok2 prog.oku2 prog.out"
 : ${DIFF=diff}
 cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -130,6 +117,7 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
+  prepare_locale_ fr $LOCALE_FR
   LANGUAGE= LC_ALL=$LOCALE_FR gst -Q prog.st > prog.out || exit 1
   ${DIFF} prog.ok prog.out > /dev/null ||
     ${DIFF} prog.ok2 prog.out > /dev/null ||
@@ -137,6 +125,7 @@ if test $LOCALE_FR != none; then
         { ${DIFF} prog.ok prog.out; exit 1; }
 fi
 if test $LOCALE_FR_UTF8 != none; then
+  prepare_locale_ fr $LOCALE_FR_UTF8
   LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 gst -Q prog.st > prog.out || exit 1
   ${DIFF} prog.oku prog.out > /dev/null ||
     ${DIFF} prog.oku2 prog.out > /dev/null ||
@@ -149,9 +138,7 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  exit 77
 fi
-
-rm -fr $tmpfiles
 
 exit 0
