Import Upstream version 0.23.1

diff --git a/gettext-tools/tests/lang-vala b/gettext-tools/tests/lang-vala
--- a/gettext-tools/tests/lang-vala
+++ b/gettext-tools/tests/lang-vala
@@ -3,7 +3,30 @@
 
 # Test of gettext facilities in the Vala language.
 # Assumes an fr_FR locale is installed.
-# Assumes the following packages are installed: vala.
+# Assumes the following packages are installed: vala or valac.
+
+# Test for presence of valac.
+(valac --version) >/dev/null 2>/dev/null
+test $? -le 1 \
+  || { echo "Skipping test: valac not found"; Exit 77; }
+
+# Test whether valac can compile a trivial program.
+cat <<\EOF > prog.vala
+int main (string[] args) {
+    return 0;
+}
+EOF
+: ${VALAC=valac}
+${VALAC} prog.vala 2>prog.err \
+  || { if grep "fatal error: 'glib\.h' file not found" < prog.err > /dev/null; then
+         echo "Skipping test: valac installation incomplete"
+         Exit 77
+       else
+         cat prog.err 1>&2
+         echo "Skipping test: valac installation does not work"
+         Exit 77
+       fi
+     }
 
 cat <<\EOF > prog.vala
 int main (string[] args) {
@@ -16,11 +39,6 @@ int main (string[] args) {
 }
 EOF
 
-# Test for presence of valac.
-(valac --version) >/dev/null 2>/dev/null
-test $? -le 1 \
-  || { echo "Skipping test: valac not found"; Exit 77; }
-
 : ${VALAC=valac}
 ${VALAC} --Xcc=-DGETTEXT_PACKAGE=\"prog\" prog.vala 2>prog.err \
   || { cat prog.err 1>&2; Exit 1; }
@@ -29,7 +47,7 @@ ${VALAC} --Xcc=-DGETTEXT_PACKAGE=\"prog\" prog.vala 2>prog.err \
 ${XGETTEXT} -o prog.tmp --omit-header --no-location prog.vala || Exit 1
 LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || Exit 1
 
-cat <<EOF > prog.ok
+cat <<\EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
 
